version: '3'
services:
  rabbitmq:
    container_name: rabbitmq-management
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
    rabbitmq-data:
        driver: local
