version: '3'
services:
   postgresdb:
     container_name: postgresdb
     image: postgres
     volumes:
        - pg-data:/var/lib/postgresql/data
     ports:
        - 5432:5432
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=onepdl
        
   pgadmin4:
     container_name: pgadmin4
     image: dpage/pgadmin4
     links:
       - postgresdb
     ports:
        - 5050:80
     environment:
       - PGADMIN_DEFAULT_EMAIL=email@domain.com
       - PGADMIN_DEFAULT_PASSWORD=postgres
        
volumes:
  pg-data:
     driver: local