version: '3'
services: 
    
  app:
    container_name: mongoexpress
    image: mongo-express
    ports: 
      -  8082:8081
    links:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports: 
      -  27017:27017
    volumes:
      -  mongo-data:/data/db
    
volumes: 
    mongo-data:
